# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'fileutils'

pillar_example_files = 'pillar/**/admin.sls.example'

Dir.glob(pillar_example_files).each do | example_file |
  pillar_file =  example_file.sub(/\.example$/, '')
  if !File.file?(pillar_file)
    puts "Note! Copying #{pillar_file} from #{example_file} ..."
    FileUtils.cp(example_file, pillar_file)
  end
end

Vagrant.configure(2) do |config|
  # Todo: Find out more about this box
  config.vm.box = "koha_saucy64"
  config.vm.box_url = "http://datatest.deichman.no/vagrant/koha_saucy64.box"

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

  # http://fgrehm.viewdocs.io/vagrant-cachier
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  config.vm.network :forwarded_port, guest: 80, host: 8000  # MARC2RDF
  config.vm.network :forwarded_port, guest: 6001, host: 6001  # SIP2
  config.vm.network :forwarded_port, guest: 8080, host: 8080  # OPAC
  config.vm.network :forwarded_port, guest: 8081, host: 8081  # INTRA
  config.vm.network :forwarded_port, guest: 3000, host: 3000  # SPARQL

  config.vm.synced_folder "salt", "/srv/salt"
  config.vm.synced_folder "pillar", "/srv/pillar"

  config.vm.provision :salt do |salt|
    salt.minion_config = "salt/minion"
    salt.run_highstate = true
    salt.verbose = true
    salt.pillar_data
  end

end
